print("Welcome to the Tip Calculator!")
total_bill = float(input("What was the total bill? $"))
tip = int(input("What percentage tip would you like to give? 10, 12, or 15? "))
new_total_bill = float(total_bill + total_bill*tip/100)
number_of_people = int(input("How many people to split the bill? "))
split_per_person = (new_total_bill/number_of_people) 
print(f"Each person should pay: ${split_per_person}")